version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - wallet-network

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "wallet"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wallet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wallet"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:4.3.0
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sns,sqs,s3,secretsmanager
    ports:
      - '4566:4566'
    networks:
      - wallet-network

  app:
    build: .
    image: wallet-service:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/wallet
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - AWS_SQS_ENDPOINT_CONFIGURATION=http://localstack:4566
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wallet-network

volumes:
  postgres-data: { }

networks:
  wallet-network:
    driver: bridge
