# Profile: test
# Shared test overrides (e.g. for integration profile).
spring:
  jpa:
    show-sql: false

jwt:
  public:
    key: classpath:certs/public.pem
  private:
    key: classpath:certs/private.pem
